Update Artist Compymono Infomation and his game information
kemono-games/fgi pull request #67
Opened 2023-11-21 02:12 UTC by PianCat

2023-11-23 21:04 UTC, ShellWen reviewed
waiting for confirmation from Compymono personally

2023-11-24 07:51 UTC, ShellWen requested changes
add "translator" to Beek Familiar Spirit

2023-11-24 07:51 UTC, ShellWen commented on games/Beek_Familiar_Spirit.yaml
> +    role: [ programmer, artist ]
add "translator"

2023-11-24 13:49 UTC, PianCat commented on games/Beek_Familiar_Spirit.yaml
> +    role: [ programmer, artist ]
@ShellWen Solved

2023-11-24 14:05 UTC, merged